# Generated by Django 4.0.6 on 2022-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('prep_time', models.IntegerField()),
                ('img', models.CharField(default='None', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
