# Generated by Django 4.1.2 on 2022-10-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_menu_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
